// Pre-built JS shim (generated by running `tsc` against src/index.ts).
// Kept in source for convenience so the app can `require` the plugin
// without a separate build step.
const { registerPlugin } = require('@capacitor/core');
const StripeTerminal = registerPlugin('StripeTerminal');
module.exports = { StripeTerminal };
